### ISSUE TITLE
Parsing multi-line messages from XCTFail can produce inaccurate results

### ISSUE THREAD

**Issue by adam-fowler** [apple/swift-corelibs-xctest#425] opened 2023-01-14 12:47 UTC
It is very hard to identify when an XCTFail message finishes in the output from XCTest.

The following test 
```swift
func testXCTFail() {
    XCTFail("""
    Test
    Failed
    """)
    print("Hello")
}
```
produces the following output
```
Test Case 'AppTests.testXCTFail' started at 2023-01-14 12:38:26.859
/workspaces/Tests/AppTests/AppTests.swift:21: error: AppTests.testFail : failed - Test
Failed
Hello
Test Case 'AppTests.testFail' failed (0.006 seconds)
```
There is no way from this output to ascertain where the fail message ends.

This is an issue for the VSCode Swift extension when parsing XCTest output to update the TestExplorer

## swift --version output
Swift version 5.8-dev (LLVM 170e2cfa496ad7c, Swift f32ae6f8c6068cd)
Target: aarch64-unknown-linux-gnu

This is an issue on all platforms

**Comment by grynspan** [comment] 2023-08-20 00:51
Duplicate of #361

**Closed by grynspan** 2023-08-20 00:51 UTC
